### ISSUE TITLE
'syncdb' command not there

### ISSUE THREAD

**Issue by haroon-github** [mhagander/pgweb#4]
Hi,

So I have been trying to follow ```docs/dev_install.rst``` and I see a step to help with creation of tables and indexes, as well as create a superuser for the local installation. That's all very good except that I can't seem to execute ```syncdb``` command. The error I get is ```Unknown command: 'syncdb' ```.

A quick look at ```./manage.py help``` output lists a lot of useful stuff but unfortunately ```syncdb``` is not one of them. Output here for reference:

```
(pgweb-p3):~/pgweb-p3/pgweb$ ./manage.py help
/home/test/pgweb-p3/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[contenttypes]
    remove_stale_contenttypes

[core]
    cleanup_old_records
    fetch_rss_feeds
    moderation_report
    sessioninfo

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[lists]
    sync_lists

[mailqueue]
    send_queued_mail

[news]
    twitter_post
    twitter_register

[security]
    update_cve_links

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver
```

Am I missing something obvious here or does the documentation need some correction/improvement ?

Regards,
Haroon

**Comment by mhagander** [comment]
Yeah, that documentation is clearly out of date -- it refers to a previous version of Django that we have not used in ages. The new command is `migrate` rather than `syncdb`.

Please also note that this repository is just a mirror of the primary one, and discussion around the pgweb development happens on the pgsql-www mailinglist, like most other parts of PostgreSQL. That's a better place to post your questions for a quicker response.
